//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

//
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
//

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class SkillList
{
    private SkillListSkill[] skillField;

    /// <remarks/>
    [XmlElement("Skill")]
    public SkillListSkill[] Skill
    {
        get
        {
            return this.skillField;
        }
        set
        {
            this.skillField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
public partial class SkillListSkill
{
    private byte damageField;

    private byte costField;

    private byte critField;

    private byte attributeField;

    private byte elementalField;

    private byte conditionField;

    private byte typField;

    private byte rangeField;

    private byte conditionChangeRateField;

    private string animationField;

    private string nameField;

    private int actioncostField;

    /// <remarks/>
    public byte Damage
    {
        get
        {
            return this.damageField;
        }
        set
        {
            this.damageField = value;
        }
    }

    /// <remarks/>
    public byte Cost
    {
        get
        {
            return this.costField;
        }
        set
        {
            this.costField = value;
        }
    }

    /// <remarks/>
    public byte Crit
    {
        get
        {
            return this.critField;
        }
        set
        {
            this.critField = value;
        }
    }

    /// <remarks/>
    public byte Attribute
    {
        get
        {
            return this.attributeField;
        }
        set
        {
            this.attributeField = value;
        }
    }

    /// <remarks/>
    public byte Elemental
    {
        get
        {
            return this.elementalField;
        }
        set
        {
            this.elementalField = value;
        }
    }

    /// <remarks/>
    public byte Condition
    {
        get
        {
            return this.conditionField;
        }
        set
        {
            this.conditionField = value;
        }
    }

    /// <remarks/>
    public byte Typ
    {
        get
        {
            return this.typField;
        }
        set
        {
            this.typField = value;
        }
    }

    /// <remarks/>
    public byte Range
    {
        get
        {
            return this.rangeField;
        }
        set
        {
            this.rangeField = value;
        }
    }

    /// <remarks/>
    public byte ConditionChangeRate
    {
        get
        {
            return this.conditionChangeRateField;
        }
        set
        {
            this.conditionChangeRateField = value;
        }
    }

    /// <remarks/>
    public string Animation
    {
        get
        {
            return this.animationField;
        }
        set
        {
            this.animationField = value;
        }
    }

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public int Actioncost
    {
        get
        {
            return this.actioncostField;
        }
        set
        {
            this.actioncostField = value;
        }
    }
}